# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTimeEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(781, 598)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.clock_label_iran = QLabel(self.tab)
        self.clock_label_iran.setObjectName(u"clock_label_iran")
        self.clock_label_iran.setGeometry(QRect(140, 160, 151, 51))
        font = QFont()
        font.setPointSize(25)
        self.clock_label_iran.setFont(font)
        self.clock_label_iran.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.clock_label_germany = QLabel(self.tab)
        self.clock_label_germany.setObjectName(u"clock_label_germany")
        self.clock_label_germany.setGeometry(QRect(150, 280, 141, 51))
        self.clock_label_germany.setFont(font)
        self.clock_label_germany.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.clock_label_usa = QLabel(self.tab)
        self.clock_label_usa.setObjectName(u"clock_label_usa")
        self.clock_label_usa.setGeometry(QRect(150, 380, 141, 61))
        self.clock_label_usa.setFont(font)
        self.clock_label_usa.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.clock_label_iran_time = QLabel(self.tab)
        self.clock_label_iran_time.setObjectName(u"clock_label_iran_time")
        self.clock_label_iran_time.setGeometry(QRect(340, 150, 211, 61))
        font1 = QFont()
        font1.setFamilies([u"Seven Segment"])
        font1.setPointSize(40)
        self.clock_label_iran_time.setFont(font1)
        self.clock_label_iran_time.setAlignment(Qt.AlignCenter)
        self.clock_label_germany_time = QLabel(self.tab)
        self.clock_label_germany_time.setObjectName(u"clock_label_germany_time")
        self.clock_label_germany_time.setGeometry(QRect(340, 260, 211, 61))
        self.clock_label_germany_time.setFont(font1)
        self.clock_label_germany_time.setAlignment(Qt.AlignCenter)
        self.clock_label_usa_time = QLabel(self.tab)
        self.clock_label_usa_time.setObjectName(u"clock_label_usa_time")
        self.clock_label_usa_time.setGeometry(QRect(340, 380, 211, 61))
        self.clock_label_usa_time.setFont(font1)
        self.clock_label_usa_time.setAlignment(Qt.AlignCenter)
        self.clock_label_gmt = QLabel(self.tab)
        self.clock_label_gmt.setObjectName(u"clock_label_gmt")
        self.clock_label_gmt.setGeometry(QRect(140, 50, 151, 51))
        self.clock_label_gmt.setFont(font)
        self.clock_label_gmt.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.clock_label_gmt_time = QLabel(self.tab)
        self.clock_label_gmt_time.setObjectName(u"clock_label_gmt_time")
        self.clock_label_gmt_time.setGeometry(QRect(340, 50, 211, 51))
        self.clock_label_gmt_time.setFont(font1)
        self.clock_label_gmt_time.setAlignment(Qt.AlignCenter)
        self.clock_label_seconds = QLabel(self.tab)
        self.clock_label_seconds.setObjectName(u"clock_label_seconds")
        self.clock_label_seconds.setGeometry(QRect(510, 40, 211, 401))
        font2 = QFont()
        font2.setFamilies([u"Seven Segment"])
        font2.setPointSize(120)
        self.clock_label_seconds.setFont(font2)
        self.clock_label_seconds.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayoutWidget = QWidget(self.tab_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(20, 130, 711, 351))
        self.alarm_grid = QGridLayout(self.gridLayoutWidget)
        self.alarm_grid.setObjectName(u"alarm_grid")
        self.alarm_grid.setContentsMargins(0, 0, 0, 0)
        self.label_alam = QLabel(self.tab_2)
        self.label_alam.setObjectName(u"label_alam")
        self.label_alam.setGeometry(QRect(20, 10, 121, 41))
        font3 = QFont()
        font3.setPointSize(17)
        self.label_alam.setFont(font3)
        self.alarm_btn_add = QPushButton(self.tab_2)
        self.alarm_btn_add.setObjectName(u"alarm_btn_add")
        self.alarm_btn_add.setGeometry(QRect(530, 80, 89, 25))
        self.alarm_time_edit = QTimeEdit(self.tab_2)
        self.alarm_time_edit.setObjectName(u"alarm_time_edit")
        self.alarm_time_edit.setGeometry(QRect(330, 80, 151, 31))
        self.alarm_txtbox = QLineEdit(self.tab_2)
        self.alarm_txtbox.setObjectName(u"alarm_txtbox")
        self.alarm_txtbox.setGeometry(QRect(90, 80, 191, 25))
        self.label = QLabel(self.tab_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(90, 60, 91, 17))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_stopwatch = QLabel(self.tab_3)
        self.label_stopwatch.setObjectName(u"label_stopwatch")
        self.label_stopwatch.setGeometry(QRect(200, 80, 311, 91))
        font4 = QFont()
        font4.setFamilies([u"Seven Segment"])
        font4.setPointSize(50)
        self.label_stopwatch.setFont(font4)
        self.label_stopwatch.setStyleSheet(u"color: rgb(145, 65, 172);")
        self.label_stopwatch.setScaledContents(False)
        self.label_stopwatch.setAlignment(Qt.AlignCenter)
        self.stopwatch_start_btn = QPushButton(self.tab_3)
        self.stopwatch_start_btn.setObjectName(u"stopwatch_start_btn")
        self.stopwatch_start_btn.setGeometry(QRect(140, 240, 131, 25))
        self.stopwatch_stop_btn = QPushButton(self.tab_3)
        self.stopwatch_stop_btn.setObjectName(u"stopwatch_stop_btn")
        self.stopwatch_stop_btn.setGeometry(QRect(290, 240, 131, 25))
        self.stopwatch_reset_btn = QPushButton(self.tab_3)
        self.stopwatch_reset_btn.setObjectName(u"stopwatch_reset_btn")
        self.stopwatch_reset_btn.setGeometry(QRect(440, 240, 131, 25))
        self.stopwatch_reset_btn.setIconSize(QSize(19, 16))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.timer_hour_txtbox = QLineEdit(self.tab_4)
        self.timer_hour_txtbox.setObjectName(u"timer_hour_txtbox")
        self.timer_hour_txtbox.setGeometry(QRect(130, 80, 161, 131))
        self.timer_hour_txtbox.setFont(font4)
        self.timer_hour_txtbox.setAlignment(Qt.AlignCenter)
        self.timer_minute_txtbox = QLineEdit(self.tab_4)
        self.timer_minute_txtbox.setObjectName(u"timer_minute_txtbox")
        self.timer_minute_txtbox.setGeometry(QRect(300, 80, 161, 131))
        self.timer_minute_txtbox.setFont(font4)
        self.timer_minute_txtbox.setAlignment(Qt.AlignCenter)
        self.timer_second_txtbox = QLineEdit(self.tab_4)
        self.timer_second_txtbox.setObjectName(u"timer_second_txtbox")
        self.timer_second_txtbox.setGeometry(QRect(470, 80, 161, 131))
        self.timer_second_txtbox.setFont(font4)
        self.timer_second_txtbox.setAlignment(Qt.AlignCenter)
        self.timer_start_btn = QPushButton(self.tab_4)
        self.timer_start_btn.setObjectName(u"timer_start_btn")
        self.timer_start_btn.setGeometry(QRect(160, 310, 131, 25))
        self.timer_stop_btn = QPushButton(self.tab_4)
        self.timer_stop_btn.setObjectName(u"timer_stop_btn")
        self.timer_stop_btn.setGeometry(QRect(310, 310, 131, 25))
        self.timer_reset_btn = QPushButton(self.tab_4)
        self.timer_reset_btn.setObjectName(u"timer_reset_btn")
        self.timer_reset_btn.setGeometry(QRect(460, 310, 131, 25))
        self.timer_reset_btn.setIconSize(QSize(19, 16))
        self.tabWidget.addTab(self.tab_4, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 781, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.clock_label_iran.setText(QCoreApplication.translate("MainWindow", u"Tehran", None))
        self.clock_label_germany.setText(QCoreApplication.translate("MainWindow", u"Berlin", None))
        self.clock_label_usa.setText(QCoreApplication.translate("MainWindow", u"NewYork", None))
        self.clock_label_iran_time.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.clock_label_germany_time.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.clock_label_usa_time.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.clock_label_gmt.setText(QCoreApplication.translate("MainWindow", u"GMT", None))
        self.clock_label_gmt_time.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.clock_label_seconds.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"World Clock", None))
        self.label_alam.setText(QCoreApplication.translate("MainWindow", u"Add Alarm:", None))
        self.alarm_btn_add.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.label_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.stopwatch_start_btn.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.stopwatch_stop_btn.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.stopwatch_reset_btn.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"StopWatch", None))
        self.timer_hour_txtbox.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.timer_minute_txtbox.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.timer_second_txtbox.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.timer_start_btn.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.timer_stop_btn.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.timer_reset_btn.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Timer", None))
    # retranslateUi

